<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Prüfungsfragen zur Lernkontrolle: Regressionsanalyse Teil 1 – Statistik als Modellierung</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/image-quiz.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Statistik als Modellierung</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Start</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./vorbereitung-lineares-modell.html"> 
<span class="menu-text">Vorbereitung: Lineares Modell</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./probepruefung-regression.html" aria-current="page"> 
<span class="menu-text">Probeprüfung: Regression</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Auf dieser Seite</h2>
   
  <ul>
  <li><a href="#ausgangsmaterial" id="toc-ausgangsmaterial" class="nav-link active" data-scroll-target="#ausgangsmaterial">Ausgangsmaterial</a>
  <ul class="collapse">
  <li><a href="#deskriptive-statistik" id="toc-deskriptive-statistik" class="nav-link" data-scroll-target="#deskriptive-statistik">Deskriptive Statistik</a></li>
  <li><a href="#ausgabe-a-einfache-lineare-regression" id="toc-ausgabe-a-einfache-lineare-regression" class="nav-link" data-scroll-target="#ausgabe-a-einfache-lineare-regression">Ausgabe A: Einfache lineare Regression</a></li>
  <li><a href="#ausgabe-b-multiple-lineare-regression" id="toc-ausgabe-b-multiple-lineare-regression" class="nav-link" data-scroll-target="#ausgabe-b-multiple-lineare-regression">Ausgabe B: Multiple lineare Regression</a></li>
  </ul></li>
  <li><a href="#teil-1-richtig-oder-falsch" id="toc-teil-1-richtig-oder-falsch" class="nav-link" data-scroll-target="#teil-1-richtig-oder-falsch">Teil 1: Richtig oder falsch?</a>
  <ul class="collapse">
  <li><a href="#aufgabe-1-einfache-regression" id="toc-aufgabe-1-einfache-regression" class="nav-link" data-scroll-target="#aufgabe-1-einfache-regression">Aufgabe 1: Einfache Regression</a></li>
  <li><a href="#aufgabe-2-koeffizienten-der-multiplen-regression" id="toc-aufgabe-2-koeffizienten-der-multiplen-regression" class="nav-link" data-scroll-target="#aufgabe-2-koeffizienten-der-multiplen-regression">Aufgabe 2: Koeffizienten der multiplen Regression</a></li>
  <li><a href="#aufgabe-3-modellgüte" id="toc-aufgabe-3-modellgüte" class="nav-link" data-scroll-target="#aufgabe-3-modellgüte">Aufgabe 3: Modellgüte</a></li>
  <li><a href="#aufgabe-4-voraussetzungen-und-diagnostik" id="toc-aufgabe-4-voraussetzungen-und-diagnostik" class="nav-link" data-scroll-target="#aufgabe-4-voraussetzungen-und-diagnostik">Aufgabe 4: Voraussetzungen und Diagnostik</a></li>
  <li><a href="#aufgabe-5-grundlagen-und-vorgehen" id="toc-aufgabe-5-grundlagen-und-vorgehen" class="nav-link" data-scroll-target="#aufgabe-5-grundlagen-und-vorgehen">Aufgabe 5: Grundlagen und Vorgehen</a></li>
  </ul></li>
  <li><a href="#teil-2-lückentexte" id="toc-teil-2-lückentexte" class="nav-link" data-scroll-target="#teil-2-lückentexte">Teil 2: Lückentexte</a>
  <ul class="collapse">
  <li><a href="#aufgabe-6-ergebnisse-beschreiben" id="toc-aufgabe-6-ergebnisse-beschreiben" class="nav-link" data-scroll-target="#aufgabe-6-ergebnisse-beschreiben">Aufgabe 6: Ergebnisse beschreiben</a></li>
  <li><a href="#aufgabe-7-werte-vorhersagen" id="toc-aufgabe-7-werte-vorhersagen" class="nav-link" data-scroll-target="#aufgabe-7-werte-vorhersagen">Aufgabe 7: Werte vorhersagen</a></li>
  <li><a href="#aufgabe-8-residuum" id="toc-aufgabe-8-residuum" class="nav-link" data-scroll-target="#aufgabe-8-residuum">Aufgabe 8: Residuum</a></li>
  <li><a href="#aufgabe-9-standardisierte-koeffizienten" id="toc-aufgabe-9-standardisierte-koeffizienten" class="nav-link" data-scroll-target="#aufgabe-9-standardisierte-koeffizienten">Aufgabe 9: Standardisierte Koeffizienten</a></li>
  <li><a href="#aufgabe-10-voraussetzungen-prüfen-in-jamovi" id="toc-aufgabe-10-voraussetzungen-prüfen-in-jamovi" class="nav-link" data-scroll-target="#aufgabe-10-voraussetzungen-prüfen-in-jamovi">Aufgabe 10: Voraussetzungen prüfen in Jamovi</a></li>
  <li><a href="#aufgabe-11-begriffe-der-regressionsgleichung" id="toc-aufgabe-11-begriffe-der-regressionsgleichung" class="nav-link" data-scroll-target="#aufgabe-11-begriffe-der-regressionsgleichung">Aufgabe 11: Begriffe der Regressionsgleichung</a></li>
  </ul></li>
  <li><a href="#teil-3-offene-fragen" id="toc-teil-3-offene-fragen" class="nav-link" data-scroll-target="#teil-3-offene-fragen">Teil 3: Offene Fragen</a>
  <ul class="collapse">
  <li><a href="#aufgabe-12-ergebnisbericht-formulieren" id="toc-aufgabe-12-ergebnisbericht-formulieren" class="nav-link" data-scroll-target="#aufgabe-12-ergebnisbericht-formulieren">Aufgabe 12: Ergebnisbericht formulieren</a></li>
  <li><a href="#aufgabe-13-eine-verletzte-voraussetzung" id="toc-aufgabe-13-eine-verletzte-voraussetzung" class="nav-link" data-scroll-target="#aufgabe-13-eine-verletzte-voraussetzung">Aufgabe 13: Eine verletzte Voraussetzung</a></li>
  <li><a href="#aufgabe-14-assoziation-oder-kausalität" id="toc-aufgabe-14-assoziation-oder-kausalität" class="nav-link" data-scroll-target="#aufgabe-14-assoziation-oder-kausalität">Aufgabe 14: Assoziation oder Kausalität</a></li>
  <li><a href="#aufgabe-15-zwei-prädiktoren-vergleichen" id="toc-aufgabe-15-zwei-prädiktoren-vergleichen" class="nav-link" data-scroll-target="#aufgabe-15-zwei-prädiktoren-vergleichen">Aufgabe 15: Zwei Prädiktoren vergleichen</a></li>
  <li><a href="#aufgabe-16-regression-oder-korrelation" id="toc-aufgabe-16-regression-oder-korrelation" class="nav-link" data-scroll-target="#aufgabe-16-regression-oder-korrelation">Aufgabe 16: Regression oder Korrelation</a></li>
  <li><a href="#aufgabe-17-schrittweise-regression" id="toc-aufgabe-17-schrittweise-regression" class="nav-link" data-scroll-target="#aufgabe-17-schrittweise-regression">Aufgabe 17: Schrittweise Regression</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Prüfungsfragen zur Lernkontrolle: Regressionsanalyse Teil 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Diese Probeprüfung hilft dir, deinen Lernstand zur linearen Regression einzuschätzen. Die Aufgabentypen entsprechen denen der Prüfung: Richtig-Falsch-Aussagen, Lückentexte und offene Fragen.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>So arbeitest du mit dieser Seite
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Beantworte die Fragen zuerst selbstständig, bevor du die Lösungen aufklappst.</li>
<li>Bei den Richtig-Falsch- und Lückentext-Aufgaben erhältst du direkt eine Rückmeldung: richtige Antworten werden grün, falsche rot markiert.</li>
<li>Bei den offenen Fragen vergleichst du deine Antwort mit der Musterlösung.</li>
<li>Du brauchst für diese Probeprüfung <strong>kein Jamovi</strong>. Alle nötigen Ergebnisse stehen in den Ausgaben unten. Wenn du die Analysen selbst nachvollziehen möchtest, kannst du den Datensatz herunterladen: <a href="daten/arbeitszufriedenheit.csv">arbeitszufriedenheit.csv</a>.</li>
<li>Rechne mit den Werten, wie sie in den Jamovi-Ausgaben stehen. Kleine Abweichungen durch Rundung sind bei den Antworten berücksichtigt.Verwende einen Punkt “.” als Dezimalzeichen.</li>
</ul>
</div>
</div>
<section id="ausgangsmaterial" class="level2">
<h2 class="anchored" data-anchor-id="ausgangsmaterial">Ausgangsmaterial</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Fiktive Daten
</div>
</div>
<div class="callout-body-container callout-body">
<p>Der Datensatz ist simuliert. Er ist so konstruiert, dass die Ergebnisse realistisch aussehen, taugt aber nicht als inhaltliche Evidenz zum Thema Arbeitszufriedenheit.</p>
</div>
</div>
<p>In Anlehnung an das Job-Demands-Resources-Modell wurde untersucht, wie <strong>Ressourcen</strong> und <strong>Anforderungen (Demands)</strong> mit der Arbeitszufriedenheit zusammenhängen. Befragt wurden 420 Beschäftigte eines Dienstleistungsunternehmens.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Rolle</th>
<th style="text-align: left;">Bedeutung</th>
<th style="text-align: left;">Wertebereich</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>zufriedenheit</code></td>
<td style="text-align: left;">Kriterium (AV)</td>
<td style="text-align: left;">Allgemeine Arbeitszufriedenheit, Mittelwertskala aus 6 Items</td>
<td style="text-align: left;">1 = sehr unzufrieden bis 7 = sehr zufrieden</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>handlungsspielraum</code></td>
<td style="text-align: left;">Ressource (UV)</td>
<td style="text-align: left;">Erlebter Entscheidungs- und Handlungsspielraum, Mittelwertskala aus 5 Items</td>
<td style="text-align: left;">1 bis 7</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>unterstuetzung</code></td>
<td style="text-align: left;">Ressource (UV)</td>
<td style="text-align: left;">Soziale Unterstützung durch die vorgesetzte Person, Mittelwertskala aus 4 Items</td>
<td style="text-align: left;">1 bis 7</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>ueberstunden</code></td>
<td style="text-align: left;">Demand (UV)</td>
<td style="text-align: left;">Überstunden pro Woche</td>
<td style="text-align: left;">0 bis 20 Stunden</td>
</tr>
</tbody>
</table>
<section id="deskriptive-statistik" class="level3">
<h3 class="anchored" data-anchor-id="deskriptive-statistik">Deskriptive Statistik</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 18%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">zufriedenheit</th>
<th style="text-align: right;">handlungsspielraum</th>
<th style="text-align: right;">unterstuetzung</th>
<th style="text-align: right;">ueberstunden</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: right;">420</td>
<td style="text-align: right;">420</td>
<td style="text-align: right;">420</td>
<td style="text-align: right;">420</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mittelwert</td>
<td style="text-align: right;">4.63</td>
<td style="text-align: right;">4.56</td>
<td style="text-align: right;">4.76</td>
<td style="text-align: right;">5.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standardabweichung</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">3.39</td>
</tr>
<tr class="even">
<td style="text-align: left;">Minimum</td>
<td style="text-align: right;">1.67</td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">2.25</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maximum</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">16</td>
</tr>
</tbody>
</table>
</section>
<section id="ausgabe-a-einfache-lineare-regression" class="level3">
<h3 class="anchored" data-anchor-id="ausgabe-a-einfache-lineare-regression">Ausgabe A: Einfache lineare Regression</h3>
<p>Kriterium <code>zufriedenheit</code>, Prädiktor <code>handlungsspielraum</code>.</p>
<div id="fig-ausgabe-a" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Jamovi-Ausgabe. Güte der Modellanpassung: R gleich 0.427, R-Quadrat gleich 0.182, adjustiertes R-Quadrat gleich 0.180, F gleich 93.3 mit df1 gleich 1 und df2 gleich 418, p kleiner .001, N gleich 420. Modellkoeffizienten für zufriedenheit: Interzept mit Schätzung 2.806, Standardfehler 0.1945, Konfidenzintervall von 2.423 bis 3.188, t gleich 14.42, p kleiner .001. Handlungsspielraum mit Schätzung 0.400, Standardfehler 0.0414, Konfidenzintervall von 0.319 bis 0.481, t gleich 9.66, p kleiner .001, standardisierter Schätzer 0.427.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ausgabe-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/jamovi-ausgabe-a.png" class="img-fluid figure-img" alt="Jamovi-Ausgabe. Güte der Modellanpassung: R gleich 0.427, R-Quadrat gleich 0.182, adjustiertes R-Quadrat gleich 0.180, F gleich 93.3 mit df1 gleich 1 und df2 gleich 418, p kleiner .001, N gleich 420. Modellkoeffizienten für zufriedenheit: Interzept mit Schätzung 2.806, Standardfehler 0.1945, Konfidenzintervall von 2.423 bis 3.188, t gleich 14.42, p kleiner .001. Handlungsspielraum mit Schätzung 0.400, Standardfehler 0.0414, Konfidenzintervall von 0.319 bis 0.481, t gleich 9.66, p kleiner .001, standardisierter Schätzer 0.427.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ausgabe-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Ausgabe A: Einfache lineare Regression mit <code>handlungsspielraum</code> als einzigem Prädiktor.
</figcaption>
</figure>
</div>
</section>
<section id="ausgabe-b-multiple-lineare-regression" class="level3">
<h3 class="anchored" data-anchor-id="ausgabe-b-multiple-lineare-regression">Ausgabe B: Multiple lineare Regression</h3>
<p>Kriterium <code>zufriedenheit</code>, Prädiktoren <code>handlungsspielraum</code>, <code>unterstuetzung</code> und <code>ueberstunden</code>.</p>
<div id="fig-ausgabe-b" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Jamovi-Ausgabe. Güte der Modellanpassung: R gleich 0.476, R-Quadrat gleich 0.226, adjustiertes R-Quadrat gleich 0.221, F gleich 40.6 mit df1 gleich 3 und df2 gleich 416, p kleiner .001, N gleich 420. Modellkoeffizienten für zufriedenheit: Interzept 3.0517, Standardfehler 0.2868, Konfidenzintervall 2.4879 bis 3.6155, t gleich 10.64, p kleiner .001. Handlungsspielraum 0.3358, Standardfehler 0.0444, Konfidenzintervall 0.2486 bis 0.4230, t gleich 7.57, p kleiner .001, standardisierter Schätzer 0.3586. Unterstuetzung 0.0776, Standardfehler 0.0526, Konfidenzintervall minus 0.0258 bis 0.1809, t gleich 1.48, p gleich .141, standardisierter Schätzer 0.0693. Ueberstunden minus 0.0608, Standardfehler 0.0136, Konfidenzintervall minus 0.0875 bis minus 0.0340, t gleich minus 4.47, p kleiner .001, standardisierter Schätzer minus 0.1980. Durbin-Watson-Autokorrelationstest: Autokorrelation minus 0.0143, DW-Statistik 2.02, p gleich .818. Kollinearitätsstatistik: handlungsspielraum VIF 1.21 und Toleranz 0.829, unterstuetzung VIF 1.19 und Toleranz 0.842, ueberstunden VIF 1.06 und Toleranz 0.946.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ausgabe-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/jamovi-ausgabe-b.png" class="img-fluid figure-img" alt="Jamovi-Ausgabe. Güte der Modellanpassung: R gleich 0.476, R-Quadrat gleich 0.226, adjustiertes R-Quadrat gleich 0.221, F gleich 40.6 mit df1 gleich 3 und df2 gleich 416, p kleiner .001, N gleich 420. Modellkoeffizienten für zufriedenheit: Interzept 3.0517, Standardfehler 0.2868, Konfidenzintervall 2.4879 bis 3.6155, t gleich 10.64, p kleiner .001. Handlungsspielraum 0.3358, Standardfehler 0.0444, Konfidenzintervall 0.2486 bis 0.4230, t gleich 7.57, p kleiner .001, standardisierter Schätzer 0.3586. Unterstuetzung 0.0776, Standardfehler 0.0526, Konfidenzintervall minus 0.0258 bis 0.1809, t gleich 1.48, p gleich .141, standardisierter Schätzer 0.0693. Ueberstunden minus 0.0608, Standardfehler 0.0136, Konfidenzintervall minus 0.0875 bis minus 0.0340, t gleich minus 4.47, p kleiner .001, standardisierter Schätzer minus 0.1980. Durbin-Watson-Autokorrelationstest: Autokorrelation minus 0.0143, DW-Statistik 2.02, p gleich .818. Kollinearitätsstatistik: handlungsspielraum VIF 1.21 und Toleranz 0.829, unterstuetzung VIF 1.19 und Toleranz 0.842, ueberstunden VIF 1.06 und Toleranz 0.946.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ausgabe-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Ausgabe B: Multiple lineare Regression mit den beiden Ressourcen und den Überstunden als Prädiktoren, inklusive Überprüfung der Voraussetzungen.
</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="teil-1-richtig-oder-falsch" class="level1">
<h1>Teil 1: Richtig oder falsch?</h1>
<p>Entscheide für jede Aussage einzeln.</p>
<section id="aufgabe-1-einfache-regression" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-1-einfache-regression">Aufgabe 1: Einfache Regression</h2>
<p>Beziehe dich auf <strong>Ausgabe A</strong>.</p>
<div class="webex-check webex-box">
<ul>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> 18.2 % der Varianz der Arbeitszufriedenheit lassen sich durch den Handlungsspielraum aufklären.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Die Korrelation zwischen Handlungsspielraum und Arbeitszufriedenheit beträgt r = .18.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Für eine Person mit einem Handlungsspielraum von 5 sagt das Modell eine Arbeitszufriedenheit von 4.81 vorher.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Der Achsenabschnitt gibt die erwartete Arbeitszufriedenheit bei einem Handlungsspielraum von 0 an und ist hier inhaltlich gut interpretierbar.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Da p &lt; .001 ist, ist belegt, dass mehr Handlungsspielraum zu höherer Arbeitszufriedenheit führt.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Erklärung zur Lösung
</button>
<ul>
<li><strong>R² = .182</strong> ist der Anteil der Varianz der Arbeitszufriedenheit, der durch den Handlungsspielraum aufgeklärt wird, also 18.2 %.</li>
<li>Die Korrelation ist die <strong>Wurzel</strong> aus R²: <span class="math inline">\(\sqrt{.182} = .43\)</span>. Der Wert .18 ist R², nicht r. In Ausgabe A steht die Korrelation auch direkt oben als R = 0.427. Weil es nur einen Prädiktor gibt, entspricht ihr hier auch der standardisierte Schätzer von 0.427.</li>
<li>Vorhersage: <span class="math inline">\(2.806 + 0.400 \cdot 5 = 4.81\)</span>.</li>
<li>Rechnerisch stimmt die Aussage zum Achsenabschnitt, inhaltlich aber nicht: Die Skala beginnt bei 1, der kleinste beobachtete Wert liegt bei 1.40. Ein Handlungsspielraum von 0 kommt gar nicht vor, der Achsenabschnitt ist hier also ein reiner Hilfswert (Extrapolation über den Datenbereich hinaus).</li>
<li>Ein kleiner p-Wert sagt nichts über Kausalität. Die Daten stammen aus einer Querschnittsbefragung ohne Intervention. Wir können also nichts über die Kausalität aussagen.</li>
</ul>
</div>
</section>
<section id="aufgabe-2-koeffizienten-der-multiplen-regression" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-2-koeffizienten-der-multiplen-regression">Aufgabe 2: Koeffizienten der multiplen Regression</h2>
<p>Beziehe dich auf <strong>Ausgabe B</strong>.</p>
<div class="webex-check webex-box">
<ul>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Pro zusätzlichem Skalenpunkt Handlungsspielraum steigt die Arbeitszufriedenheit um durchschnittlich 0.3358 Punkte, wenn Unterstützung und Überstunden konstant gehalten werden.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Der Vergleich der unstandardisierten Koeffizienten (0.3358 gegenüber −0.0608) zeigt, dass die Überstunden den schwächsten Effekt haben.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Der Effekt von <code>unterstuetzung</code> ist statistisch nicht signifikant; das 95 %-Konfidenzintervall schliesst die Null ein.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Mehr Überstunden gehen im Mittel mit geringerer Arbeitszufriedenheit einher – bei gleichem Handlungsspielraum und gleicher Unterstützung.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Der nicht signifikante p-Wert von <code>unterstuetzung</code> beweist, dass es in der Population keinen Zusammenhang gibt.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Das 95 %-Konfidenzintervall von <code>handlungsspielraum</code> bedeutet, dass Werte unter 0.2486 mit den Daten gut vereinbar sind.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Erklärung zur Lösung
</button>
<ul>
<li>Der Koeffizient einer multiplen Regression ist immer ein <strong>Ceteris-paribus-Effekt</strong>: Er gilt unter der Annahme, dass die anderen Prädiktoren unverändert bleiben.</li>
<li>Die unstandardisierten Koeffizienten sind hier <strong>nicht vergleichbar</strong>: 0.3358 bezieht sich auf einen Skalenpunkt, −0.0608 auf eine Überstunde pro Woche. Die standardisierten Koeffizienten zeigen das Gegenteil der Aussage: Mit β = −.198 sind die Überstunden der zweitstärkste Prädiktor, am schwächsten ist die Unterstützung mit β = .069.</li>
<li>Bei <code>unterstuetzung</code> ist p = .141 und das Intervall reicht von −0.0258 bis 0.1809, schliesst also die Null ein. Ein nicht signifikantes Ergebnis heisst aber nur, dass die Nullhypothese nicht verworfen wird – es ist <strong>kein Beleg dafür, dass der Effekt null ist</strong>. Hier sind auch Effekte bis 0.1809 Skalenpunkte mit den Daten vereinbar.</li>
<li>Werte <strong>innerhalb</strong> des Konfidenzintervalls sind mit den Daten gut vereinbar, Werte ausserhalb (also unter 0.2486) gerade nicht.</li>
</ul>
</div>
</section>
<section id="aufgabe-3-modellgüte" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-3-modellgüte">Aufgabe 3: Modellgüte</h2>
<p>Beziehe dich auf <strong>Ausgabe B</strong>.</p>
<div class="webex-check webex-box">
<ul>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Die drei Prädiktoren klären zusammen 22.6 % der Varianz der Arbeitszufriedenheit auf.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> R² = .226 heisst, dass 22.6 % der Befragten korrekt vorhergesagt werden.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Das adjustierte R² ist kleiner als R², weil es die Anzahl der Prädiktoren berücksichtigt.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Der F-Test prüft, ob das Modell insgesamt mehr Varianz aufklärt, als bei reinen Zufallsvariablen zu erwarten wäre.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Auch bei der multiplen Regression entspricht R² dem quadrierten Korrelationskoeffizienten zwischen einem einzelnen Prädiktor und dem Kriterium.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Erklärung zur Lösung
</button>
<p>R² bezieht sich immer auf <strong>Varianz</strong>, nicht auf Personen oder Fälle. Bei der einfachen Regression entspricht R² tatsächlich der quadrierten Korrelation zwischen UV und AV (Ausgabe A: <span class="math inline">\(0.427^2 = 0.182\)</span>). Bei der multiplen Regression ist R² dagegen die quadrierte Korrelation zwischen den <strong>beobachteten und den vorhergesagten Werten</strong> (multiples R = .476).</p>
</div>
</section>
<section id="aufgabe-4-voraussetzungen-und-diagnostik" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-4-voraussetzungen-und-diagnostik">Aufgabe 4: Voraussetzungen und Diagnostik</h2>
<div class="webex-check webex-box">
<ul>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Die abhängige Variable muss normalverteilt sein.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Die Residuen sollen näherungsweise normalverteilt sein.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Mit VIF-Werten von 1.06 bis 1.21 ist Multikollinearität in Ausgabe B unproblematisch.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Die Durbin-Watson-Statistik von 2.02 spricht gegen eine Abhängigkeit der Fehlerwerte.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Heteroskedastizität verzerrt in erster Linie die geschätzten Regressionskoeffizienten.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Ein trichterförmiges Muster im Diagramm der Residuen gegen die vorhergesagten Werte deutet auf eine Verletzung der Homoskedastizität hin.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Erklärung zur Lösung
</button>
<p>Normalverteilt sein sollen <strong>nur die Fehlerwerte (Residuen)</strong>, weder die Prädiktoren noch das Kriterium. Als Faustregel für Multikollinearität gilt VIF &lt; 10, für die Durbin-Watson-Statistik ein Wert zwischen 1 und 3.</p>
<p>Sowohl eine verletzte Normalverteilung der Residuen als auch Heteroskedastizität verfälschen <strong>nicht die Koeffizienten</strong>, sondern deren <strong>Standardfehler</strong> – und damit p-Werte und Konfidenzintervalle.</p>
</div>
</section>
<section id="aufgabe-5-grundlagen-und-vorgehen" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-5-grundlagen-und-vorgehen">Aufgabe 5: Grundlagen und Vorgehen</h2>
<div class="webex-check webex-box">
<ul>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> OLS bestimmt die Gerade mit der kleinsten Summe der quadrierten Residuen.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Ein Residuum ist der tatsächliche (beobachtete) Wert minus den vorhergesagten Wert.</li>
<li><select class="webex-select"><option value="blank"></option><option value="">richtig</option><option value="answer">falsch</option></select> Schrittweise Verfahren (Stepwise Regression) sind das empfohlene Standardvorgehen zur Auswahl der Prädiktoren.</li>
<li><select class="webex-select"><option value="blank"></option><option value="answer">richtig</option><option value="">falsch</option></select> Bei verletzter Normalverteilung der Residuen ist Bootstrapping eine mögliche Vorgehensweise.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Erklärung zur Lösung
</button>
<p>Ein <strong>positives Residuum</strong> bedeutet, dass die Person zufriedener ist, als das Modell vorhersagt; ein negatives Residuum, dass sie unzufriedener ist. Die Regressionsgerade minimiert die Summe der <strong>quadrierten</strong> Residuen – dadurch fallen grosse Abweichungen stärker ins Gewicht als kleine.</p>
</div>
<hr>
</section>
</section>
<section id="teil-2-lückentexte" class="level1">
<h1>Teil 2: Lückentexte</h1>
<p>Trage deine Antworten in die Felder ein. Pro Lücke gibt es 1 Punkt. Zahlen bitte ohne Einheit eingeben, als Dezimaltrennzeichen dient der Punkt.</p>
<section id="aufgabe-6-ergebnisse-beschreiben" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-6-ergebnisse-beschreiben">Aufgabe 6: Ergebnisse beschreiben</h2>
<p>Beziehe dich auf <strong>Ausgabe B</strong>.</p>
<div class="webex-check webex-box">
<p>Das Gesamtmodell klärt <input class="webex-solveme nospaces" data-tol="0.1" size="4" data-answer="[&quot;22.6&quot;]"> % der Varianz der Arbeitszufriedenheit auf. Der Prädiktor mit dem stärksten Effekt ist <select class="webex-select"><option value="blank"></option><option value="answer">handlungsspielraum</option><option value="">unterstuetzung</option><option value="">ueberstunden</option></select>. Der Koeffizient bei <code>ueberstunden</code> bedeutet, dass die Arbeitszufriedenheit pro zusätzlicher Überstunde pro Woche um <input class="webex-solveme nospaces" size="6" data-answer="[&quot;0.0608&quot;,&quot;0.061&quot;,&quot;0.06&quot;]"> Skalenpunkte <select class="webex-select"><option value="blank"></option><option value="">steigt</option><option value="answer">sinkt</option></select>.</p>
</div>
</section>
<section id="aufgabe-7-werte-vorhersagen" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-7-werte-vorhersagen">Aufgabe 7: Werte vorhersagen</h2>
<p>Eine Person gibt einen Handlungsspielraum von 5 an, eine Unterstützung von 4 und leistet 6 Überstunden pro Woche. Verwende <strong>Ausgabe B</strong>.</p>
<div class="webex-check webex-box">
<p>Die Regressionsgleichung lautet: <span class="math inline">\(\hat{y} =\)</span> <input class="webex-solveme nospaces" data-tol="0.01" size="4" data-answer="[&quot;3.05&quot;]"> <span class="math inline">\(+\)</span> <input class="webex-solveme nospaces" data-tol="0.005" size="5" data-answer="[&quot;0.336&quot;,&quot;.336&quot;]"> <span class="math inline">\(\cdot \text{handlungsspielraum} + 0.0776 \cdot \text{unterstuetzung} - 0.0608 \cdot \text{ueberstunden}\)</span></p>
<p>Die vorhergesagte Arbeitszufriedenheit beträgt <input class="webex-solveme nospaces" data-tol="0.03" size="4" data-answer="[&quot;4.68&quot;]">.</p>
</div>
<div class="webex-solution">
<button>
Rechenweg anzeigen
</button>
<p><span class="math display">\[
\hat{y} = 3.05 + 0.336 \cdot 5 + 0.0776 \cdot 4 - 0.0608 \cdot 6
\]</span> <span class="math display">\[
\hat{y} = 3.05 + 1.68 + 0.31 - 0.36 = 4.68
\]</span></p>
<p>Beachte: Auch der nicht signifikante Prädiktor <code>unterstuetzung</code> geht in die Vorhersage ein, solange er im Modell enthalten ist.</p>
</div>
</section>
<section id="aufgabe-8-residuum" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-8-residuum">Aufgabe 8: Residuum</h2>
<p>Die Person aus Aufgabe 7 gibt tatsächlich eine Arbeitszufriedenheit von 5.33 an.</p>
<div class="webex-check webex-box">
<p>Ihr Residuum beträgt <input class="webex-solveme nospaces" data-tol="0.03" size="4" data-answer="[&quot;0.65&quot;,&quot;.65&quot;]"> Skalenpunkte. Die Person ist also <select class="webex-select"><option value="blank"></option><option value="answer">zufriedener</option><option value="">unzufriedener</option></select> als vom Modell vorhergesagt.</p>
</div>
<div class="webex-solution">
<button>
Rechenweg anzeigen
</button>
<p>Das Residuum ist der tatsächliche (beobachtete) Wert minus den vorhergesagten Wert: <span class="math display">\[
e = y - \hat{y} = 5.33 - 4.68 = 0.65
\]</span> Ein <strong>positives</strong> Residuum heisst: Die Person liegt über der Regressionsgeraden, ist also zufriedener, als das Modell erwarten lässt.</p>
</div>
</section>
<section id="aufgabe-9-standardisierte-koeffizienten" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-9-standardisierte-koeffizienten">Aufgabe 9: Standardisierte Koeffizienten</h2>
<div class="webex-check webex-box">
<p>Standardisierte Koeffizienten verwenden für alle Variablen die <input class="webex-solveme nospaces ignorecase" size="22" data-answer="[&quot;Standardabweichung&quot;,&quot;Standardabweichungen&quot;,&quot;SD&quot;]"> als Einheit. Sie geben an, um wie viele <input class="webex-solveme nospaces ignorecase" size="22" data-answer="[&quot;Standardabweichungen&quot;,&quot;Standardabweichung&quot;,&quot;SD&quot;]"> sich das Kriterium verändert, wenn sich der Prädiktor um eine Einheit dieser Grösse verändert und alle anderen Prädiktoren <select class="webex-select"><option value="blank"></option><option value="answer">unverändert bleiben</option><option value="">gleich stark steigen</option><option value="">aus dem Modell entfernt werden</option></select>.</p>
</div>
<div class="webex-solution">
<button>
Nachgerechnet
</button>
<p>Du kannst die standardisierten Koeffizienten aus der deskriptiven Statistik nachrechnen: <span class="math display">\[
\beta_j = b_j \cdot \frac{s_{x_j}}{s_y} = 0.3358 \cdot \frac{1.11}{1.04} = 0.3586
\]</span></p>
</div>
</section>
<section id="aufgabe-10-voraussetzungen-prüfen-in-jamovi" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-10-voraussetzungen-prüfen-in-jamovi">Aufgabe 10: Voraussetzungen prüfen in Jamovi</h2>
<div class="webex-check webex-box">
<p>Die Linearität prüfen wir über einen <select class="webex-select"><option value="blank"></option><option value="answer">Scatterplot</option><option value="">Boxplot</option><option value="">Q-Q-Plot</option></select> mit einer <input class="webex-solveme nospaces ignorecase" size="10" data-answer="[&quot;LOESS&quot;,&quot;Loess&quot;,&quot;LOWESS&quot;]">-Linie. Ob die Residuen normalverteilt sind, sehen wir im <select class="webex-select"><option value="blank"></option><option value="">Scatterplot</option><option value="">Histogramm der AV</option><option value="answer">Q-Q-Plot oder Histogramm der Residuen</option></select>. Die Unabhängigkeit der Fehlerwerte prüfen wir mit der <input class="webex-solveme nospaces ignorecase" size="20" data-answer="[&quot;Durbin-Watson&quot;,&quot;Durbin Watson&quot;,&quot;Durbin-Watson-Statistik&quot;]">-Statistik.</p>
</div>
<div class="webex-solution">
<button>
Wo finde ich das in Jamovi?
</button>
<ul>
<li><strong>Scatterplot mit LOESS</strong>: Analysen &gt; JJStatsPlot &gt; Scatter Plot</li>
<li><strong>Q-Q-Plot, Residuendiagramme, Durbin-Watson und Kollinearitätsstatistik</strong>: direkt im Menü der linearen Regression unter «Annahmeprüfungen»</li>
<li><strong>Residuen speichern</strong> (z. B. für ein Histogramm): im Menü der Regression unter «Speichern» die «Residuen» anwählen</li>
</ul>
</div>
</section>
<section id="aufgabe-11-begriffe-der-regressionsgleichung" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-11-begriffe-der-regressionsgleichung">Aufgabe 11: Begriffe der Regressionsgleichung</h2>
<p>Gegeben ist die Gleichung <span class="math inline">\(y = b_0 + b_1 x_1 + b_2 x_2 + e\)</span>.</p>
<div class="webex-check webex-box">
<p><span class="math inline">\(b_0\)</span> heisst <select class="webex-select"><option value="blank"></option><option value="answer">Achsenabschnitt</option><option value="">Steigung</option><option value="">Residuum</option></select>, <span class="math inline">\(b_1\)</span> und <span class="math inline">\(b_2\)</span> heissen <select class="webex-select"><option value="blank"></option><option value="">Achsenabschnitte</option><option value="answer">Regressionskoeffizienten</option><option value="">Standardfehler</option></select> und <span class="math inline">\(e\)</span> steht für das <input class="webex-solveme nospaces ignorecase" size="14" data-answer="[&quot;Residuum&quot;,&quot;Residuen&quot;,&quot;Fehler&quot;,&quot;Fehlerwert&quot;]">. Der Koeffizient <span class="math inline">\(b_1\)</span> gibt den Effekt von <span class="math inline">\(x_1\)</span> unter sonst gleichen Bedingungen an, lateinisch <input class="webex-solveme nospaces ignorecase" size="18" data-answer="[&quot;ceteris paribus&quot;,&quot;ceteris-paribus&quot;]">.</p>
</div>
<hr>
</section>
</section>
<section id="teil-3-offene-fragen" class="level1">
<h1>Teil 3: Offene Fragen</h1>
<p>Formuliere deine Antwort zuerst selbst und vergleiche sie dann mit der Musterlösung.</p>
<section id="aufgabe-12-ergebnisbericht-formulieren" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-12-ergebnisbericht-formulieren">Aufgabe 12: Ergebnisbericht formulieren</h2>
<p>Formuliere auf Basis von <strong>Ausgabe B</strong> einen Ergebnisabschnitt von vier bis sechs Sätzen, wie er in einer Arbeit stehen könnte. Gehe auf das Gesamtmodell und auf alle drei Prädiktoren ein.</p>
<div class="webex-solution">
<button>
Musterlösung
</button>
<p>Das Modell klärt einen signifikanten Anteil der Varianz der Arbeitszufriedenheit auf, R² = .226, adj. R² = .221, F(3, 416) = 40.6, p &lt; .001. Der Handlungsspielraum hängt positiv mit der Arbeitszufriedenheit zusammen: Pro zusätzlichem Skalenpunkt steigt sie bei konstant gehaltenen übrigen Prädiktoren um durchschnittlich 0.34 Punkte, 95 %-CI [0.25, 0.42], p &lt; .001. Die Überstunden hängen negativ mit der Arbeitszufriedenheit zusammen, b = −0.06 Punkte pro Überstunde, 95 %-CI [−0.09, −0.03], p &lt; .001. [Optional, zur Veranschaulichung der absoluten Effektstärke]: Über eine Spannweite von 16 Überstunden entspricht das rund einem ganzen Skalenpunkt. Für die soziale Unterstützung durch die vorgesetzte Person zeigte sich kein signifikanter Zusammenhang, b = 0.08, p = .141. [Optional, zur Veranschaulichung des Konfidenzintervalls:] Das Konfidenzintervall schliesst allerdings auch Effekte bis 0.18 Punkte ein. Anhand der standardisierten Koeffizienten ist der Handlungsspielraum der stärkste Prädiktor (β = .36), gefolgt von den Überstunden (β = −.20).</p>
<p><strong>Darauf kommt es an</strong></p>
<ul>
<li>Gesamtmodell mit R², adjustiertem R² und ggf. auch F-Test berichtet</li>
<li>alle drei Koeffizienten in ihren Originaleinheiten interpretiert, inklusive Ceteris-paribus-Bedingung</li>
<li>Signifikanzen korrekt eingeordnet</li>
<li>nicht signifikanter Prädiktor korrekt formuliert, also ohne die Aussage, es gebe keinen Zusammenhang (weil: absence of evidence is not evidence of absence!)</li>
</ul>
</div>
</section>
<section id="aufgabe-13-eine-verletzte-voraussetzung" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-13-eine-verletzte-voraussetzung">Aufgabe 13: Eine verletzte Voraussetzung</h2>
<p>Im Diagramm der Residuen gegen die vorhergesagten Werte zeigt sich ein deutlich trichterförmiges Muster: Bei hohen vorhergesagten Werten streuen die Residuen stark, bei tiefen kaum.</p>
<ol type="a">
<li>Welche Voraussetzung ist verletzt?</li>
<li>Welche Ergebnisse der Regression sind betroffen und welche nicht?</li>
<li>Nenne eine mögliche Vorgehensweise.</li>
</ol>
<div class="webex-solution">
<button>
Musterlösung
</button>
<ol type="a">
<li><p>Die <strong>Homoskedastizität</strong>. Die Varianz der Residuen ist nicht über den gesamten Wertebereich gleich.</p></li>
<li><p>Die geschätzten <strong>Koeffizienten bleiben unverzerrt</strong>. Verfälscht werden die <strong>Standardfehler</strong> und damit alles, was darauf aufbaut: t-Werte, p-Werte und Konfidenzintervalle. Aussagen zur Signifikanz sind also nicht mehr vertrauenswürdig.</p></li>
<li><p><strong>Bootstrapping</strong> (alternativ: robuste Standardfehler oder eine Transformation der abhängigen Variable).</p></li>
</ol>
</div>
</section>
<section id="aufgabe-14-assoziation-oder-kausalität" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-14-assoziation-oder-kausalität">Aufgabe 14: Assoziation oder Kausalität</h2>
<p>Aus <strong>Ausgabe A</strong> folgt: «Die Arbeitszufriedenheit steigt durchschnittlich um 0.40 Punkte pro zusätzlichem Skalenpunkt Handlungsspielraum.» Zwei Personen interpretieren das unterschiedlich:</p>
<ul>
<li><strong>Person A:</strong> Wenn wir zwei Beschäftigte vergleichen und Person B erlebt einen Skalenpunkt mehr Handlungsspielraum, dann erwarten wir für B eine um 0.40 Punkte höhere Arbeitszufriedenheit.</li>
<li><strong>Person B:</strong> Wenn wir den Arbeitsplatz einer Person so umgestalten, dass sie einen Skalenpunkt mehr Handlungsspielraum erlebt, dann steigt ihre Arbeitszufriedenheit um 0.40 Punkte.</li>
</ul>
<p>Welche Interpretation ist durch die Analyse gedeckt? Begründe und nenne einen konkreten Grund, weshalb die andere problematisch ist.</p>
<div class="webex-solution">
<button>
Musterlösung
</button>
<p>Gedeckt ist die Interpretation von <strong>Person A</strong>. Die Regression beschreibt einen <strong>Vergleich zwischen Beobachtungen</strong>: Beschäftigte mit mehr erlebtem Handlungsspielraum sind im Durchschnitt zufriedener.</p>
<p>Person B formuliert eine <strong>kausale und kontrafaktische</strong> Aussage darüber, was passiert, wenn man bei derselben Person eingreift. Das lässt sich aus Querschnittsdaten ohne Intervention nicht schliessen. Mögliche konkrete Gründe:</p>
<ul>
<li><strong>Drittvariablen</strong>: Hierarchiestufe, Führungsqualität, Art der Tätigkeit oder Persönlichkeitsmerkmale (z. B. negative Affektivität) beeinflussen beides.</li>
<li><strong>Umgekehrte Kausalität</strong>: Wer zufrieden ist, nimmt den eigenen Spielraum möglicherweise grösser wahr, oder bekommt tatsächlich mehr Spielraum zugestanden.</li>
<li><strong>Common-Method-Bias</strong>: Beide Variablen stammen aus derselben Selbstauskunft zum selben Zeitpunkt.</li>
</ul>
</div>
</section>
<section id="aufgabe-15-zwei-prädiktoren-vergleichen" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-15-zwei-prädiktoren-vergleichen">Aufgabe 15: Zwei Prädiktoren vergleichen</h2>
<p>Ein Student schreibt: «Die Überstunden sind der unwichtigste Prädiktor, weil ihr Koeffizient mit −0.0608 den kleinsten Betrag hat.» Nimm Stellung und begründe mit den Zahlen aus <strong>Ausgabe B</strong>.</p>
<div class="webex-solution">
<button>
Musterlösung
</button>
<p>Die Aussage ist nicht haltbar. Unstandardisierte Koeffizienten hängen von der <strong>Einheit und der Streuung</strong> des jeweiligen Prädiktors ab. Beim Handlungsspielraum bedeutet «eine Einheit» einen Skalenpunkt auf einer siebenstufigen Skala (SD = 1.11), bei den Überstunden eine einzelne Stunde pro Woche bei einer Streuung von 3.39 Stunden. Über den beobachteten Bereich von 0 bis 16 Überstunden summiert sich der Effekt auf <span class="math inline">\(16 \cdot (-0.0608) = -0.97\)</span> Skalenpunkte.</p>
<p>Der Vergleich gelingt über die <strong>standardisierten Koeffizienten</strong>: β = .3586 für den Handlungsspielraum, β = −.1980 für die Überstunden und nur β = .0693 für die Unterstützung. Die Überstunden sind also der zweitstärkste Prädiktor, nicht der schwächste.</p>
</div>
</section>
<section id="aufgabe-16-regression-oder-korrelation" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-16-regression-oder-korrelation">Aufgabe 16: Regression oder Korrelation</h2>
<p>Welche Informationen liefert eine einfache lineare Regression, die eine Produkt-Moment-Korrelation nicht liefert? Nenne zwei Punkte und erkläre, wann man deshalb die Regression wählt.</p>
<div class="webex-solution">
<button>
Musterlösung
</button>
<ol type="1">
<li>Die Regression liefert eine <strong>Gleichung mit Achsenabschnitt und Steigung in den Originaleinheiten</strong>. Sie quantifiziert den Zusammenhang also inhaltlich («0.40 Skalenpunkte Zufriedenheit pro Skalenpunkt Handlungsspielraum») und erlaubt konkrete <strong>Vorhersagen</strong>.</li>
<li>Die Regression lässt sich um <strong>weitere Prädiktoren erweitern</strong>. Damit können Störvariablen kontrolliert und Effekte ceteris paribus geschätzt werden.</li>
</ol>
<p>Die Korrelation liefert nur Richtung und Stärke des Zusammenhangs und ist symmetrisch, unterscheidet also nicht zwischen UV und AV. Die Regression wählt man deshalb immer dann, wenn eine gerichtete Fragestellung vorliegt, wenn vorhergesagt werden bzw. der Zusammenhang anhand konkreter Einheiten quantifiziert werden soll oder wenn weitere Variablen berücksichtigt werden müssen.</p>
</div>
</section>
<section id="aufgabe-17-schrittweise-regression" class="level2">
<h2 class="anchored" data-anchor-id="aufgabe-17-schrittweise-regression">Aufgabe 17: Schrittweise Regression</h2>
<p>Eine Kollegin schlägt vor, aus 20 verfügbaren Variablen per schrittweiser Regression automatisch die besten Prädiktoren auswählen zu lassen. Was entgegnest du? Nenne zwei Gründe und einen Alternativvorschlag.</p>
<div class="webex-solution">
<button>
Musterlösung
</button>
<ol type="1">
<li>Schrittweise Verfahren liefern <strong>instabile Resultate</strong>. Welche Variablen im Modell landen, hängt stark von Zufallsschwankungen der Stichprobe ab; eine neue Stichprobe führt oft zu einem anderen Modell.</li>
<li>Die resultierenden <strong>p-Werte und Konfidenzintervalle dürfen nicht wie üblich interpretiert werden</strong>, weil dieselben Daten sowohl für die Auswahl der Variablen als auch für deren Testung verwendet wurden.</li>
</ol>
<p><strong>Alternative:</strong> theoriegeleitete Auswahl der Prädiktoren mit Einschluss (ENTER), gestützt auf bestehende Literatur und inhaltliche Überlegungen. Wird bewusst explorativ gearbeitet, muss das als solches deklariert und das Ergebnis idealerweise an neuen Daten überprüft werden.</p>
</div>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Und jetzt?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wenn dir einzelne Aufgaben schwergefallen sind, lohnt sich ein Blick in die entsprechenden Folien der Sitzungen zur Regressionsanalyse. Inhalte aus den Bachelor-Vorlesungen finden sich unter <a href="https://djfgerber.github.io/aps_statistik1/index.html" target="_blank">Quantitative Methoden 2</a> oder <a href="https://mdsteiner.github.io/quantitative_methoden_3/" target="_blank">Quantitative Methoden 3</a></p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script>



/* update total correct if #webex-total_correct exists */

update_total_correct = function() {

  console.log("webex: update total_correct");



  var t = document.getElementsByClassName("webex-total_correct");

  for (var i = 0; i < t.length; i++) {

    p = t[i].parentElement;

    var correct = p.getElementsByClassName("webex-correct").length;

    var solvemes = p.getElementsByClassName("webex-solveme").length;

    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;

    var selects = p.getElementsByClassName("webex-select").length;



    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";

  }

}



/* webex-solution button toggling function */

b_func = function() {

  console.log("webex: toggle hide");



  var cl = this.parentElement.classList;

  if (cl.contains('open')) {

    cl.remove("open");

  } else {

    cl.add("open");

  }

}



/* check answers */

check_func = function() {

  console.log("webex: check answers");



  var cl = this.parentElement.classList;

  if (cl.contains('unchecked')) {

    cl.remove("unchecked");

    this.innerHTML = "Antworten ausblenden";

  } else {

    cl.add("unchecked");

    this.innerHTML = "Antworten prüfen";

  }

}



/* function for checking solveme answers */

solveme_func = function(e) {

  console.log("webex: check solveme");



  var real_answers = JSON.parse(this.dataset.answer);

  var my_answer = this.value;

  var cl = this.classList;

  if (cl.contains("ignorecase")) {

    my_answer = my_answer.toLowerCase();

  }

  if (cl.contains("nospaces")) {

    my_answer = my_answer.replace(/ /g, "")

  }



  if (my_answer == "") {

    cl.remove("webex-correct");

    cl.remove("webex-incorrect");

  } else if (real_answers.includes(my_answer)) {

    cl.add("webex-correct");

    cl.remove("webex-incorrect");

  } else {

    cl.add("webex-incorrect");

    cl.remove("webex-correct");

  }



  // match numeric answers within a specified tolerance

  if(this.dataset.tol > 0){

    var tol = JSON.parse(this.dataset.tol);

    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)

    if (matches.reduce((a, b) => a + b, 0) > 0) {

      cl.add("webex-correct");

    } else {

      cl.remove("webex-correct");

    }

  }



  // added regex bit

  if (cl.contains("regex")){

    answer_regex = RegExp(real_answers.join("|"))

    if (answer_regex.test(my_answer)) {

      cl.add("webex-correct");

    }

  }



  update_total_correct();

}



/* function for checking select answers */

select_func = function(e) {

  console.log("webex: check select");



  var cl = this.classList



  /* add style */

  cl.remove("webex-incorrect");

  cl.remove("webex-correct");

  if (this.value == "answer") {

    cl.add("webex-correct");

  } else if (this.value != "blank") {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



/* function for checking radiogroups answers */

radiogroups_func = function(e) {

  console.log("webex: check radiogroups");



  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');

  var cl = checked_button.parentElement.classList;

  var labels = checked_button.parentElement.parentElement.children;



  /* get rid of styles */

  for (i = 0; i < labels.length; i++) {

    labels[i].classList.remove("webex-incorrect");

    labels[i].classList.remove("webex-correct");

  }



  /* add style */

  if (checked_button.value == "answer") {

    cl.add("webex-correct");

  } else {

    cl.add("webex-incorrect");

  }



  update_total_correct();

}



window.onload = function() {

  console.log("webex onload");

  /* set up solution buttons */

  var buttons = document.getElementsByTagName("button");



  for (var i = 0; i < buttons.length; i++) {

    if (buttons[i].parentElement.classList.contains('webex-solution')) {

      buttons[i].onclick = b_func;

    }

  }



  var check_sections = document.getElementsByClassName("webex-check");

  console.log("check:", check_sections.length);

  for (var i = 0; i < check_sections.length; i++) {

    check_sections[i].classList.add("unchecked");



    let btn = document.createElement("button");

    btn.innerHTML = "Antworten prüfen";

    btn.classList.add("webex-check-button");

    btn.onclick = check_func;

    check_sections[i].appendChild(btn);



    let spn = document.createElement("span");

    spn.classList.add("webex-total_correct");

    check_sections[i].appendChild(spn);

  }



  /* set up webex-solveme inputs */

  var solveme = document.getElementsByClassName("webex-solveme");



  for (var i = 0; i < solveme.length; i++) {

    /* make sure input boxes don't auto-anything */

    solveme[i].setAttribute("autocomplete","off");

    solveme[i].setAttribute("autocorrect", "off");

    solveme[i].setAttribute("autocapitalize", "off");

    solveme[i].setAttribute("spellcheck", "false");

    solveme[i].value = "";



    /* adjust answer for ignorecase or nospaces */

    var cl = solveme[i].classList;

    var real_answer = solveme[i].dataset.answer;

    if (cl.contains("ignorecase")) {

      real_answer = real_answer.toLowerCase();

    }

    if (cl.contains("nospaces")) {

      real_answer = real_answer.replace(/ /g, "");

    }

    solveme[i].dataset.answer = real_answer;



    /* attach checking function */

    solveme[i].onkeyup = solveme_func;

    solveme[i].onchange = solveme_func;



    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  /* set up radiogroups */

  var radiogroups = document.getElementsByClassName("webex-radiogroup");

  for (var i = 0; i < radiogroups.length; i++) {

    radiogroups[i].onchange = radiogroups_func;

  }



  /* set up selects */

  var selects = document.getElementsByClassName("webex-select");

  for (var i = 0; i < selects.length; i++) {

    selects[i].onchange = select_func;

    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")

  }



  update_total_correct();

}



</script>

<script>
/*
 * Klickbare Bild-Kacheln für Quiz-Fragen.
 * Jede Kachel (.image-quiz-item) lässt sich per Klick an-/abwählen
 * (Klasse "selected"). Ein Klick auf ".image-quiz-check-btn" vergleicht die
 * Auswahl mit dem Attribut data-correct="true"/"false" jeder Kachel, färbt
 * sie entsprechend ein und zeigt die Trefferquote an.
 * ".image-quiz-reset-btn" setzt die Kacheln wieder zurück.
 */
document.addEventListener("DOMContentLoaded", function () {
  var quizzes = document.getElementsByClassName("image-quiz");

  for (var q = 0; q < quizzes.length; q++) {
    (function (quiz) {
      var items = quiz.getElementsByClassName("image-quiz-item");
      var checkBtn = quiz.querySelector(".image-quiz-check-btn");
      var resetBtn = quiz.querySelector(".image-quiz-reset-btn");
      var result = quiz.querySelector(".image-quiz-result");
      var checked = false;

      var i;
      for (i = 0; i < items.length; i++) {
        items[i].setAttribute("aria-pressed", "false");
        items[i].addEventListener("click", function () {
          if (checked) return;
          var isSelected = this.classList.toggle("selected");
          this.setAttribute("aria-pressed", isSelected ? "true" : "false");
        });
      }

      if (checkBtn) {
        checkBtn.addEventListener("click", function () {
          var correctCount = 0;
          for (var j = 0; j < items.length; j++) {
            var item = items[j];
            var isCorrect = item.dataset.correct === "true";
            var isSelected = item.classList.contains("selected");
            item.classList.remove("image-quiz-correct", "image-quiz-incorrect");
            if (isSelected === isCorrect) {
              item.classList.add("image-quiz-correct");
              correctCount++;
            } else {
              item.classList.add("image-quiz-incorrect");
            }
          }
          checked = true;
          if (result) {
            result.textContent = correctCount + " von " + items.length + " Diagrammen richtig beurteilt.";
          }
          checkBtn.disabled = true;
        });
      }

      if (resetBtn) {
        resetBtn.addEventListener("click", function () {
          for (var k = 0; k < items.length; k++) {
            items[k].classList.remove("selected", "image-quiz-correct", "image-quiz-incorrect");
            items[k].setAttribute("aria-pressed", "false");
          }
          if (result) {
            result.textContent = "";
          }
          checked = false;
          if (checkBtn) checkBtn.disabled = false;
        });
      }
    })(quizzes[q]);
  }
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>